version: "3.8"

services:
  sftp:
    image: atmoz/sftp
    volumes:
      - sftp_data:/home
    ports:
      - "2222:22"
    command: >
      qe1:pass:::ingress/
      qe2:pass:::ingress/
      qe3:pass:::ingress/
      qe4:pass:::ingress/
      qe5:pass:::ingress/
      qe6:pass:::ingress/
      observe:pass:::log/

  workflow:
    build:
      context: .
      dockerfile: Dockerfile.workflow
      args:
        REPO_URL: ${REPO_URL}
    volumes:
      - sftp_data:/SFTP
    depends_on:
      - sftp

volumes:
  sftp_data:
    driver: local
    driver_opts:
      type: "none"
      device: ${VOLUME_PATH}
      o: "bind"
